import type { User, Deed, Challenge, Achievement, LeaderboardEntry, ActivityDay, CommunityPost } from '@/types'

export const currentUser: User = {
  id: 'user-1',
  name: 'Zeid Al-Rashid',
  email: 'zeid@example.com',
  avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=ZeidAlRashid',
  xp: 47850,
  level: 23,
  maxXp: 50000,
  coins: 892,
  energy: { current: 65, max: 100 },
  streak: 14,
  rank: 'Legacy Maker',
  joinDate: '2024-01-15',
  bio: 'Seeking growth through discipline and devotion. On a journey to embody the five branches of the spiritual tree.',
  location: 'Medina, SA',
  achievements: ['ach-1', 'ach-2', 'ach-4', 'ach-6', 'ach-9', 'ach-11'],
  branches: {
    worship: {
      level: 18,
      xp: 8900,
      maxXp: 10000,
      color: '#4edea3',
      completedDeeds: 142,
      totalDeeds: 180,
      description: 'Vitality and growth through daily devotion',
      icon: '🌿',
    },
    knowledge: {
      level: 14,
      xp: 5200,
      maxXp: 7000,
      color: '#60a5fa',
      completedDeeds: 98,
      totalDeeds: 140,
      description: 'Clarity and depth through learning',
      icon: '📘',
    },
    discipline: {
      level: 21,
      xp: 11500,
      maxXp: 13000,
      color: '#ffb95f',
      completedDeeds: 203,
      totalDeeds: 250,
      description: 'Heat, refinement, and fire through practice',
      icon: '🔥',
    },
    character: {
      level: 11,
      xp: 3400,
      maxXp: 5500,
      color: '#c084fc',
      completedDeeds: 67,
      totalDeeds: 120,
      description: 'Nobility and internal strength',
      icon: '💜',
    },
    charity: {
      level: 9,
      xp: 2100,
      maxXp: 4000,
      color: '#ffb3af',
      completedDeeds: 45,
      totalDeeds: 90,
      description: 'Compassion and heart-centered action',
      icon: '🌸',
    },
  },
}

export const deeds: Deed[] = [
  {
    id: 'd-1',
    title: 'Fajr Prayer',
    description: 'Complete the Fajr prayer at its appointed time before sunrise.',
    branch: 'worship',
    xpReward: 150,
    coinReward: 25,
    energyCost: 5,
    difficulty: 'medium',
    completed: true,
    streak: 14,
    estimatedMinutes: 10,
  },
  {
    id: 'd-2',
    title: 'Read 5 Pages of Quran',
    description: 'Read with tajweed and contemplation.',
    branch: 'knowledge',
    xpReward: 200,
    coinReward: 30,
    energyCost: 10,
    difficulty: 'medium',
    completed: false,
    streak: 7,
    estimatedMinutes: 20,
  },
  {
    id: 'd-3',
    title: '30-Minute Workout',
    description: 'Maintain your physical vessel through disciplined exercise.',
    branch: 'discipline',
    xpReward: 250,
    coinReward: 35,
    energyCost: 20,
    difficulty: 'hard',
    completed: false,
    streak: 21,
    estimatedMinutes: 30,
  },
  {
    id: 'd-4',
    title: 'Morning Dhikr',
    description: 'Complete the morning remembrance supplications.',
    branch: 'worship',
    xpReward: 100,
    coinReward: 15,
    energyCost: 5,
    difficulty: 'easy',
    completed: true,
    streak: 30,
    estimatedMinutes: 15,
  },
  {
    id: 'd-5',
    title: 'Study Islamic History',
    description: 'Read one chapter from a scholarly work on Islamic history.',
    branch: 'knowledge',
    xpReward: 175,
    coinReward: 25,
    energyCost: 15,
    difficulty: 'medium',
    completed: false,
    streak: 3,
    estimatedMinutes: 45,
  },
  {
    id: 'd-6',
    title: 'Act of Charity',
    description: 'Give sadaqah or help someone in need today.',
    branch: 'charity',
    xpReward: 300,
    coinReward: 50,
    energyCost: 10,
    difficulty: 'medium',
    completed: false,
    streak: 5,
    estimatedMinutes: 20,
  },
  {
    id: 'd-7',
    title: 'Cold Shower',
    description: 'Build mental fortitude through cold immersion.',
    branch: 'discipline',
    xpReward: 120,
    coinReward: 20,
    energyCost: 8,
    difficulty: 'hard',
    completed: true,
    streak: 9,
    estimatedMinutes: 5,
  },
  {
    id: 'd-8',
    title: 'Forgive Someone',
    description: 'Practice active forgiveness for a grievance, no matter how small.',
    branch: 'character',
    xpReward: 200,
    coinReward: 30,
    energyCost: 10,
    difficulty: 'medium',
    completed: false,
    streak: 2,
    estimatedMinutes: 5,
  },
  {
    id: 'd-9',
    title: 'Tahajjud Prayer',
    description: 'Wake in the last third of the night for voluntary prayer.',
    branch: 'worship',
    xpReward: 500,
    coinReward: 80,
    energyCost: 25,
    difficulty: 'legendary',
    completed: false,
    streak: 0,
    estimatedMinutes: 20,
  },
  {
    id: 'd-10',
    title: 'No Social Media',
    description: 'Spend the full day without scrolling social media.',
    branch: 'discipline',
    xpReward: 180,
    coinReward: 28,
    energyCost: 0,
    difficulty: 'hard',
    completed: false,
    streak: 1,
    estimatedMinutes: 0,
  },
  {
    id: 'd-11',
    title: 'Visit a Family Member',
    description: 'Maintain family ties (silat al-rahm) with a visit or call.',
    branch: 'charity',
    xpReward: 150,
    coinReward: 22,
    energyCost: 15,
    difficulty: 'easy',
    completed: false,
    streak: 4,
    estimatedMinutes: 60,
  },
  {
    id: 'd-12',
    title: 'Memorize New Ayah',
    description: 'Commit one new verse of the Quran to memory.',
    branch: 'knowledge',
    xpReward: 220,
    coinReward: 35,
    energyCost: 12,
    difficulty: 'medium',
    completed: false,
    streak: 6,
    estimatedMinutes: 30,
  },
]

export const challenges: Challenge[] = [
  {
    id: 'ch-1',
    title: '30-Day Fajr Streak',
    description: 'Complete Fajr prayer every single day for 30 days without missing.',
    branch: 'worship',
    participants: 1247,
    goal: 30,
    current: 14,
    xpReward: 5000,
    coinReward: 750,
    endDate: new Date(Date.now() + 16 * 86400000).toISOString(),
    joined: true,
    rarity: 'epic',
  },
  {
    id: 'ch-2',
    title: 'Knowledge Marathon',
    description: 'Read 100 pages of Islamic scholarship within 14 days.',
    branch: 'knowledge',
    participants: 834,
    goal: 100,
    current: 42,
    xpReward: 3500,
    coinReward: 500,
    endDate: new Date(Date.now() + 8 * 86400000).toISOString(),
    joined: true,
    rarity: 'rare',
  },
  {
    id: 'ch-3',
    title: 'Iron Will: 21-Day Discipline',
    description: 'Complete all 3 daily discipline deeds for 21 consecutive days.',
    branch: 'discipline',
    participants: 2103,
    goal: 21,
    current: 0,
    xpReward: 8000,
    coinReward: 1200,
    endDate: new Date(Date.now() + 21 * 86400000).toISOString(),
    joined: false,
    rarity: 'legendary',
  },
  {
    id: 'ch-4',
    title: 'Community Compass',
    description: 'Perform 10 acts of charity in one month.',
    branch: 'charity',
    participants: 567,
    goal: 10,
    current: 0,
    xpReward: 2500,
    coinReward: 400,
    endDate: new Date(Date.now() + 25 * 86400000).toISOString(),
    joined: false,
    rarity: 'rare',
  },
  {
    id: 'ch-5',
    title: 'Mirror of the Soul',
    description: 'Journal your character reflections daily for 7 days.',
    branch: 'character',
    participants: 392,
    goal: 7,
    current: 3,
    xpReward: 1800,
    coinReward: 280,
    endDate: new Date(Date.now() + 4 * 86400000).toISOString(),
    joined: true,
    rarity: 'common',
  },
]

export const achievements: Achievement[] = [
  {
    id: 'ach-1',
    title: 'First Light',
    description: 'Complete your very first deed.',
    icon: '⭐',
    earned: true,
    earnedDate: '2024-01-16',
    rarity: 'common',
    xpReward: 100,
  },
  {
    id: 'ach-2',
    title: 'Streak Starter',
    description: 'Maintain a 7-day streak.',
    icon: '🔥',
    earned: true,
    earnedDate: '2024-01-22',
    rarity: 'common',
    branch: 'discipline',
    xpReward: 200,
  },
  {
    id: 'ach-3',
    title: 'Centurion',
    description: 'Complete 100 total deeds.',
    icon: '💯',
    earned: false,
    rarity: 'rare',
    xpReward: 500,
  },
  {
    id: 'ach-4',
    title: 'Tree Blossoms',
    description: 'Unlock all 5 branches of the Spiritual Tree.',
    icon: '🌳',
    earned: true,
    earnedDate: '2024-02-10',
    rarity: 'epic',
    xpReward: 1000,
  },
  {
    id: 'ach-5',
    title: 'Diamond Devotee',
    description: 'Maintain a 30-day streak.',
    icon: '💎',
    earned: false,
    rarity: 'epic',
    branch: 'worship',
    xpReward: 1500,
  },
  {
    id: 'ach-6',
    title: 'Scholar',
    description: 'Reach Level 10 in the Knowledge branch.',
    icon: '📚',
    earned: true,
    earnedDate: '2024-03-05',
    rarity: 'rare',
    branch: 'knowledge',
    xpReward: 750,
  },
  {
    id: 'ach-7',
    title: 'Legacy Forged',
    description: 'Reach the rank of Legacy Maker.',
    icon: '👑',
    earned: false,
    rarity: 'legendary',
    xpReward: 5000,
  },
  {
    id: 'ach-8',
    title: 'Generous Heart',
    description: 'Complete 50 charity deeds.',
    icon: '❤️',
    earned: false,
    rarity: 'rare',
    branch: 'charity',
    xpReward: 600,
  },
  {
    id: 'ach-9',
    title: 'Iron Body',
    description: 'Complete 100 discipline deeds.',
    icon: '⚔️',
    earned: true,
    earnedDate: '2024-04-20',
    rarity: 'epic',
    branch: 'discipline',
    xpReward: 1200,
  },
  {
    id: 'ach-10',
    title: 'Community Pillar',
    description: 'Join and complete 5 challenges.',
    icon: '🏛️',
    earned: false,
    rarity: 'rare',
    xpReward: 800,
  },
  {
    id: 'ach-11',
    title: 'Night Owl',
    description: 'Complete Tahajjud prayer 10 times.',
    icon: '🌙',
    earned: true,
    earnedDate: '2024-05-14',
    rarity: 'epic',
    branch: 'worship',
    xpReward: 1000,
  },
  {
    id: 'ach-12',
    title: 'Transcendent',
    description: 'Reach Level 50 overall.',
    icon: '✨',
    earned: false,
    rarity: 'legendary',
    xpReward: 10000,
  },
  {
    id: 'ach-13',
    title: 'Virtue Master',
    description: 'Reach Level 20 in the Character branch.',
    icon: '🎭',
    earned: false,
    rarity: 'epic',
    branch: 'character',
    xpReward: 2000,
  },
  {
    id: 'ach-14',
    title: 'The Dedicated',
    description: 'Log in for 60 consecutive days.',
    icon: '🗓️',
    earned: false,
    rarity: 'legendary',
    xpReward: 3000,
  },
  {
    id: 'ach-15',
    title: 'Branch Master',
    description: 'Reach Level 25 in any single branch.',
    icon: '🏆',
    earned: false,
    rarity: 'legendary',
    xpReward: 5000,
  },
]

export const leaderboard: LeaderboardEntry[] = [
  { rank: 1, userId: 'u-a', name: 'Omar Ibn Khattab', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=OmarKhattab', xp: 98450, level: 42, streak: 87, userRank: 'Legacy Maker', isCurrentUser: false },
  { rank: 2, userId: 'u-b', name: 'Aisha Nur', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=AishaNur', xp: 91200, level: 39, streak: 63, userRank: 'Legend', isCurrentUser: false },
  { rank: 3, userId: 'u-c', name: 'Ibrahim Al-Khalil', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=IbrahimKhalil', xp: 84700, level: 36, streak: 45, userRank: 'Legend', isCurrentUser: false },
  { rank: 4, userId: 'u-d', name: 'Fatima Zahra', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=FatimaZahra', xp: 76300, level: 33, streak: 52, userRank: 'Elder', isCurrentUser: false },
  { rank: 5, userId: 'u-e', name: 'Yusuf Al-Siddiq', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=YusufSiddiq', xp: 68900, level: 31, streak: 38, userRank: 'Elder', isCurrentUser: false },
  { rank: 6, userId: 'u-f', name: 'Maryam Tahir', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=MaryamTahir', xp: 62100, level: 29, streak: 29, userRank: 'Sage', isCurrentUser: false },
  { rank: 7, userId: 'u-g', name: 'Abdullah Hassan', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=AbdullahHassan', xp: 57400, level: 27, streak: 21, userRank: 'Sage', isCurrentUser: false },
  { rank: 8, userId: 'u-h', name: 'Khadijah Malik', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=KhadijahMalik', xp: 54200, level: 26, streak: 18, userRank: 'Sage', isCurrentUser: false },
  { rank: 9, userId: 'u-i', name: 'Bilal Ameen', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=BilalAmeen', xp: 51800, level: 25, streak: 15, userRank: 'Sage', isCurrentUser: false },
  { rank: 10, userId: 'u-j', name: 'Ruqayyah Said', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=RuqayyahSaid', xp: 50100, level: 24, streak: 12, userRank: 'Master', isCurrentUser: false },
  { rank: 11, userId: 'user-1', name: 'Zeid Al-Rashid', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=ZeidAlRashid', xp: 47850, level: 23, streak: 14, userRank: 'Legacy Maker', isCurrentUser: true },
  { rank: 12, userId: 'u-l', name: 'Sana Qureshi', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=SanaQureshi', xp: 45300, level: 22, streak: 9, userRank: 'Master', isCurrentUser: false },
  { rank: 13, userId: 'u-m', name: 'Hamza Rashid', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=HamzaRashid', xp: 43100, level: 21, streak: 7, userRank: 'Master', isCurrentUser: false },
  { rank: 14, userId: 'u-n', name: 'Zainab Farooq', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=ZainabFarooq', xp: 41800, level: 21, streak: 11, userRank: 'Master', isCurrentUser: false },
  { rank: 15, userId: 'u-o', name: 'Ismail Badr', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=IsmailBadr', xp: 39500, level: 20, streak: 5, userRank: 'Adept', isCurrentUser: false },
  { rank: 16, userId: 'u-p', name: 'Hafsa Noor', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=HafsaNoor', xp: 37200, level: 19, streak: 8, userRank: 'Adept', isCurrentUser: false },
  { rank: 17, userId: 'u-q', name: 'Tariq Mansoor', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=TariqMansoor', xp: 34800, level: 18, streak: 3, userRank: 'Adept', isCurrentUser: false },
  { rank: 18, userId: 'u-r', name: 'Layla Hamdan', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=LaylaHamdan', xp: 32100, level: 17, streak: 6, userRank: 'Adept', isCurrentUser: false },
  { rank: 19, userId: 'u-s', name: 'Nour Al-Din', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=NourAlDin', xp: 29400, level: 16, streak: 2, userRank: 'Devotee', isCurrentUser: false },
  { rank: 20, userId: 'u-t', name: 'Amira Khalil', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=AmiraKhalil', xp: 27800, level: 15, streak: 4, userRank: 'Devotee', isCurrentUser: false },
]

export const weeklyActivity: ActivityDay[] = [
  { day: 'Mon', worship: 3, knowledge: 2, discipline: 4, character: 1, charity: 2, total: 12 },
  { day: 'Tue', worship: 4, knowledge: 3, discipline: 3, character: 2, charity: 1, total: 13 },
  { day: 'Wed', worship: 5, knowledge: 4, discipline: 5, character: 3, charity: 3, total: 20 },
  { day: 'Thu', worship: 3, knowledge: 2, discipline: 4, character: 1, charity: 2, total: 12 },
  { day: 'Fri', worship: 6, knowledge: 5, discipline: 5, character: 4, charity: 4, total: 24 },
  { day: 'Sat', worship: 4, knowledge: 3, discipline: 3, character: 2, charity: 1, total: 13 },
  { day: 'Sun', worship: 5, knowledge: 4, discipline: 6, character: 3, charity: 3, total: 21 },
]

export const communityPosts: CommunityPost[] = [
  { id: 'cp-1', userId: 'u-a', userName: 'Omar Ibn Khattab', userAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=OmarKhattab', userRank: 'Legacy Maker', deed: 'Completed Tahajjud Prayer', branch: 'worship', xpEarned: 500, timestamp: new Date(Date.now() - 5 * 60000).toISOString(), likes: 24, liked: false },
  { id: 'cp-2', userId: 'u-b', userName: 'Aisha Nur', userAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=AishaNur', userRank: 'Legend', deed: 'Read 5 Pages of Quran', branch: 'knowledge', xpEarned: 200, timestamp: new Date(Date.now() - 18 * 60000).toISOString(), likes: 17, liked: true },
  { id: 'cp-3', userId: 'u-c', userName: 'Ibrahim Al-Khalil', userAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=IbrahimKhalil', userRank: 'Legend', deed: '30-Minute Workout', branch: 'discipline', xpEarned: 250, timestamp: new Date(Date.now() - 45 * 60000).toISOString(), likes: 31, liked: false },
  { id: 'cp-4', userId: 'u-d', userName: 'Fatima Zahra', userAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=FatimaZahra', userRank: 'Elder', deed: 'Act of Charity', branch: 'charity', xpEarned: 300, timestamp: new Date(Date.now() - 2 * 3600000).toISOString(), likes: 42, liked: false },
  { id: 'cp-5', userId: 'u-e', userName: 'Yusuf Al-Siddiq', userAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=YusufSiddiq', userRank: 'Elder', deed: 'Forgave someone today', branch: 'character', xpEarned: 200, timestamp: new Date(Date.now() - 4 * 3600000).toISOString(), likes: 58, liked: true },
  { id: 'cp-6', userId: 'u-f', userName: 'Maryam Tahir', userAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=MaryamTahir', userRank: 'Sage', deed: 'Morning Dhikr — 30-day streak!', branch: 'worship', xpEarned: 350, timestamp: new Date(Date.now() - 6 * 3600000).toISOString(), likes: 89, liked: false },
]
